### ISSUE TITLE
Security issue in package

### ISSUE THREAD

**Issue by eileenmcnaughton** [3sd/tivy#1]
![screenshot 2018-08-07 11 16 35](https://user-images.githubusercontent.com/336308/43745549-791cdc6c-9a33-11e8-9a27-08375b24d82d.png)

**Comment by michaelmcandrew** [comment]
thanks, @eileenmcnaughton - was just in the dev dependencies (which never get installed if you are using this as a drupal theme but have updated them in any case.

**Comment by michaelmcandrew** [comment]
(https://github.com/3sd/tivy/commit/4b7a60f0ea5bb4bdba8a9366dc6411a05c5c3aae)

**Comment by eileenmcnaughton** [comment]
Thanks @michaelmcandrew - we did decide it wasn't a problem but these things cause quite a bit of chatter (we were notified in several ways) so great to have fixed

**Comment by michaelmcandrew** [comment]
yeah, i thought as much, hence the fix
